import fs from "node:fs";
import path from "node:path";

// Attribute GENERATED bytes per source using sourcemap mappings (VLQ decode).
const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
function decodeVLQ(str) {
  const res = []; let shift = 0, value = 0;
  for (const c of str) {
    const d = B64.indexOf(c);
    const cont = d & 32;
    value += (d & 31) << shift;
    if (cont) { shift += 5; } else {
      const neg = value & 1;
      value >>= 1;
      res.push(neg ? (value === 0 ? -0x80000000 : -value) : value);
      value = 0; shift = 0;
    }
  }
  return res;
}

const target = process.argv[2];
const map = JSON.parse(fs.readFileSync(`${target}.map`, "utf8"));
const gen = fs.readFileSync(target, "utf8");
const lines = gen.split("\n");
const groups = {};
let srcIdx = 0;
const segLines = map.mappings.split(";");
for (let li = 0; li < segLines.length; li++) {
  if (!segLines[li]) continue;
  const lineLen = (lines[li] || "").length;
  const segs = segLines[li].split(",").filter(Boolean);
  let genCol = 0;
  const parsed = [];
  for (const s of segs) {
    const f = decodeVLQ(s);
    genCol += f[0];
    if (f.length >= 4) srcIdx += f[1];
    parsed.push({ col: genCol, src: f.length >= 4 ? srcIdx : null });
  }
  for (let i = 0; i < parsed.length; i++) {
    const start = parsed[i].col;
    const end = i + 1 < parsed.length ? parsed[i + 1].col : lineLen;
    const len = Math.max(0, end - start);
    const s = parsed[i].src == null ? "(unmapped)" : map.sources[parsed[i].src];
    let key;
    if (s === "(unmapped)") key = s;
    else if (/node_modules/.test(s)) {
      const m = s.match(/node_modules\/(@[^/]+\/[^/]+|[^/]+)/);
      key = `npm:${m ? m[1] : "?"}`;
    } else key = s.replace(/^.*?(src|shared)\//, "$1/").split("?")[0];
    groups[key] = (groups[key] || 0) + len;
  }
}
const total = fs.statSync(target).size;
const sorted = Object.entries(groups).sort((a, b) => b[1] - a[1]);
console.log(`${path.basename(target)}: ${(total / 1024).toFixed(1)} kB generated`);
let acc = 0;
for (const [k, v] of sorted.slice(0, 20)) {
  acc += v;
  console.log(`  ${(v / 1024).toFixed(1).padStart(8)} kB  ${((v / total) * 100).toFixed(1).padStart(5)}%  ${k}`);
}
console.log(`  (top 20 = ${(acc / 1024).toFixed(1)} kB)`);
