import { TARGETS } from "../../shared/catalog.js";

const restaurantPhoneSubjectLayers = [
  {
    image: "/assets/products/tapote-restaurant-phone-hand-cutout-v1.webp",
    mask: "/assets/products/tapote-restaurant-phone-mask-v2.webp",
  },
  {
    image: "/assets/products/tapote-restaurant-phone-hand-cutout-v1.webp",
    mask: "/assets/products/tapote-restaurant-hand-mask-v2.webp",
  },
];

// Une fiche correspond à un vrai univers d’achat et de mise en scène.
// Les sous-métiers proches partagent le même décor et le même parcours client.
const sectorRows = [
  {
    id: "cafe",
    slug: "cafes-bars",
    title: "Cafés & bars",
    description: "Avis, fidélité et Wi-Fi au moment du paiement ou de l’accueil.",
    placement: "Sur le comptoir, juste à côté du terminal de paiement.",
    script: "« Si vous avez aimé, vous pouvez tapoter ici. »",
    image: "/assets/products/tapote-bg-cafe-empty-v3.webp",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Restauration & commerce",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 2, plaque: 0 },
    actionIds: ["avis", "fidelite", "wifi"],
  },
  {
    id: "restaurant",
    slug: "restaurants-traiteurs-food-trucks",
    title: "Restaurants, traiteurs & food trucks",
    description: "Menu toujours à jour, réservation et avis sans recherche ni application.",
    placement: "Sur table, au comptoir ou près du point de retrait.",
    script: "« La carte est ici ; après le repas, vous pouvez aussi nous laisser un avis. »",
    image: "/assets/products/tapote-bg-restaurant-live-screen-v1.webp",
    category: "Restauration & commerce",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 2, plaque: 0 },
    actionIds: ["menu", "reservation", "avis"],
  },
  {
    id: "boulangerie",
    slug: "boulangeries-patisseries",
    title: "Boulangeries & pâtisseries",
    description: "Avis Google en priorité, puis fidélité et commandes spéciales.",
    placement: "À la caisse, dans le geste naturel qui suit le paiement.",
    script: "« Un tap ici et vous pouvez nous laisser votre avis. »",
    image: "/assets/products/tapote-bg-boulangerie-empty-v2.png",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Restauration & commerce",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["avis", "fidelite", "commande"],
  },
  {
    id: "salon",
    slug: "beaute-coiffure-bien-etre",
    title: "Beauté, coiffure & bien-être",
    description: "Réservation du prochain créneau, avis et réseaux dans un même univers.",
    placement: "À l’accueil, au miroir ou sur la table de soin.",
    script: "« Votre prochaine réservation est juste ici. »",
    image: "/assets/products/tapote-bg-beaute-empty-v2.png",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Beauté & bien-être",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["reservation", "avis", "instagram"],
  },
  {
    id: "cabinet_medical",
    slug: "cabinets-medicaux-paramedicaux",
    title: "Cabinets médicaux & paramédicaux",
    description: "Rendez-vous et informations générales, sans exposer de donnée patient.",
    placement: "Sur le bureau ou à l’accueil, dans un espace clairement identifié.",
    script: "« Les informations pratiques et la prise de rendez-vous sont ici. »",
    image: "/assets/products/tapote-bg-medical-v1.webp",
    category: "Santé & soins",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["reservation", "site", "formulaire"],
  },
  {
    id: "boutique",
    slug: "boutiques-commerces",
    title: "Boutiques & commerces",
    description: "Fidélité en priorité, puis avis, catalogue et réseaux sociaux.",
    placement: "À la caisse ou dans l’espace conseil.",
    script: "« Vos avantages et la suite de la collection sont ici. »",
    image: "/assets/products/tapote-bg-retail-v1.webp",
    category: "Restauration & commerce",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["fidelite", "avis", "instagram"],
  },
  {
    id: "hotel",
    slug: "hebergements-tourisme",
    title: "Hébergements & tourisme",
    description: "Guide d’accueil, Wi-Fi, services et bonnes adresses sur une seule entrée.",
    placement: "À la réception, dans l’entrée ou dans les espaces communs.",
    script: "« Wi-Fi, horaires et bonnes adresses : tout est ici. »",
    image: "/assets/products/tapote-bg-hotel-v1.webp",
    category: "Hébergement & tourisme",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 2, plaque: 3 },
    actionIds: ["multiliens", "wifi", "avis"],
  },
  {
    id: "auto_ecole",
    slug: "auto-ecoles",
    title: "Auto-écoles",
    description: "Avis Google après la formation ou l’examen, puis planning et inscription.",
    placement: "À l’accueil, après une leçon ou au retour d’examen.",
    script: "« Si la formation vous a plu, vous pouvez laisser votre avis ici. »",
    image: "/assets/products/tapote-bg-auto-ecole-v1.webp",
    category: "Services, agences & mobilité",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["avis", "reservation", "formulaire"],
  },
  {
    id: "garage",
    slug: "garages-mobilite",
    title: "Garages & mobilité",
    description: "Avis Google après la restitution du véhicule, puis entretien et contact.",
    placement: "Sur le comptoir de réception, au moment de rendre les clés.",
    script: "« Si tout s’est bien passé, votre avis est à un tap. »",
    image: "/assets/products/tapote-bg-automobile-v1.webp",
    category: "Services, agences & mobilité",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["avis", "reservation", "contact"],
  },
  {
    id: "artisan",
    slug: "artisans-services-terrain",
    title: "Artisans & services terrain",
    description: "Avis Google en priorité, puis contact, portfolio et site internet.",
    placement: "Dans la poche ou présenté à la fin de l’intervention.",
    script: "« Si le travail vous a plu, vous pouvez laisser votre avis ici. »",
    image: "/assets/products/tapote-bg-artisan-v1.webp",
    category: "Services, agences & mobilité",
    recommendedProductId: "carte",
    composition: { comptoir: 0, plaque: 0 },
    actionIds: ["avis", "contact", "site"],
  },
  {
    id: "immobilier",
    slug: "agences-independants",
    title: "Agences & indépendants",
    description: "Coordonnées, prise de rendez-vous, documents et page multi-liens.",
    placement: "Sur le bureau ou présenté pendant un rendez-vous et une visite.",
    script: "« Mes coordonnées et les documents utiles sont ici. »",
    image: "/assets/products/tapote-bg-agence-empty-v2.png",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Services, agences & mobilité",
    recommendedProductId: "carte",
    composition: { comptoir: 0, plaque: 0 },
    actionIds: ["contact", "multiliens", "reservation"],
  },
  {
    id: "salle_sport",
    slug: "sport-studios",
    title: "Sport, fitness & studios",
    description: "Planning et réservation des séances, fidélité et communauté.",
    placement: "À l’accueil ou à l’entrée du studio.",
    script: "« Le planning et la réservation de votre prochaine séance sont ici. »",
    image: "/assets/products/tapote-bg-sport-empty-v2.png",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Sport & collectif",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 2, plaque: 3 },
    actionIds: ["reservation", "fidelite", "instagram"],
  },
  {
    id: "coworking",
    slug: "bureaux-formation",
    title: "Bureaux, coworking & formation",
    description: "Wi-Fi, programmes, inscription, salles et informations pratiques.",
    placement: "À l’accueil et dans les salles partagées.",
    script: "« Wi-Fi, inscription et ressources : tout est ici. »",
    image: "/assets/products/tapote-bg-formation-empty-v2.png",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Bureaux & événements",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 2, plaque: 3 },
    actionIds: ["multiliens", "wifi", "formulaire"],
  },
  {
    id: "evenement",
    slug: "evenements-culture-associations",
    title: "Événements, culture & associations",
    description: "Programme, billetterie, inscription, dons et liens utiles au même endroit.",
    placement: "À l’entrée, au point d’accueil ou près du programme.",
    script: "« Le programme, les billets et les informations sont ici. »",
    image: "/assets/products/tapote-bg-evenement-empty-v2.png",
    subjectLayers: restaurantPhoneSubjectLayers,
    category: "Bureaux & événements",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 2, plaque: 3 },
    actionIds: ["multiliens", "paiement", "instagram"],
  },
  {
    id: "veterinaire",
    slug: "animaux-soins",
    title: "Animaux & soins",
    description: "Rendez-vous, conseils, contact et avis pour vétérinaires et toiletteurs.",
    placement: "À l’accueil, près du carnet ou au moment de rendre l’animal.",
    script: "« Le prochain rendez-vous et les informations utiles sont ici. »",
    image: "/assets/products/tapote-bg-animaux-v1.webp",
    category: "Santé & soins",
    recommendedProductId: "pack_duo",
    composition: { comptoir: 1, plaque: 1 },
    actionIds: ["reservation", "avis", "site"],
  },
];

export const SECTORS = sectorRows.map((row) => ({
  ...TARGETS[row.id],
  ...row,
  exampleBrand: "VOTRE MARQUE",
  promise: `${row.title} : l’usage prioritaire est déjà choisi, les autres restent accessibles en un geste.`,
}));

export const SECTOR_CATEGORIES = [...new Set(SECTORS.map((sector) => sector.category))];

export const findSectorBySlug = (slug) => SECTORS.find((sector) => sector.slug === slug);
