export const SHIPPING = {
  freeThreshold: 5900,
  standardPrice: 490,
};

export const calculateShipping = (subtotal) => (
  subtotal >= SHIPPING.freeThreshold ? 0 : SHIPPING.standardPrice
);

export const PRODUCTS = {
  plaque: {
    id: "plaque",
    name: "La Plaque 12 × 12",
    shortName: "Plaque 12 × 12",
    price: 3900,
    description: "Plaque premium NFC + QR, pensée pour les comptoirs et les murs.",
    format: "PMMA imprimé · 120 × 120 mm · adhésif ou socle",
    badge: "Nouveau",
    previewType: "square",
    recommendedFor: "Avis, réseaux et réservation",
  },
  comptoir: {
    id: "comptoir",
    name: "Le Comptoir A6",
    shortName: "Comptoir A6",
    price: 4900,
    description: "Chevalet plexiglas transparent, insert client et NFC dissimulé.",
    format: "Plexiglas L · insert A6 105 × 148 mm",
    badge: "Best-seller",
    previewType: "portrait",
    recommendedFor: "Comptoir et accueil",
  },
  table6: {
    id: "table6",
    name: "Les Chevalets A6 ×6",
    shortName: "A6 ×6",
    price: 13900,
    description: "Six chevalets A6 produits ensemble à partir d’un même gabarit.",
    format: "6 chevalets plexiglas · 1 design partagé · 6 liens possibles",
    badge: "Multi-zone",
    previewType: "portrait",
    recommendedFor: "Restaurant et réseau",
  },
  carte: {
    id: "carte",
    name: "La Carte",
    shortName: "Carte",
    price: 2990,
    description: "Le Tapote mobile pour les équipes, artisans et commerciaux.",
    format: "PVC premium · 85 × 54 mm",
    badge: "Mobile",
    previewType: "landscape",
    recommendedFor: "Équipe et terrain",
  },
  sticker: {
    id: "sticker",
    name: "La Vitrine",
    shortName: "Vitrine",
    price: 2990,
    description: "Un sticker NFC + QR résistant qui agit même après la fermeture.",
    format: "Vinyle extérieur laminé · 90 × 90 mm",
    badge: "Extérieur",
    previewType: "square",
    recommendedFor: "Vitrine et porte",
  },
  mini: {
    id: "mini",
    name: "Le Mini Comptoir",
    shortName: "Mini 8 × 8",
    price: 3400,
    description: "Une plaque compacte, stable et discrète pour les petits espaces.",
    format: "PMMA imprimé · 80 × 80 mm · mini-socle",
    badge: "Compact",
    previewType: "square",
    recommendedFor: "Caisse et cabine",
  },
  pack_essentiel: {
    id: "pack_essentiel",
    kind: "pack",
    name: "Pack Essentiel",
    shortName: "Pack Essentiel",
    price: 5900,
    value: 6890,
    description: "Le duo simple pour démarrer au comptoir et garder Tapote en main.",
    format: "1 Plaque 12 × 12 · 1 Carte · 1 destination",
    badge: "Pour démarrer",
    defaultAction: "avis",
    features: ["Design aux couleurs du commerce", "NFC + QR configurés et testés", "BAT et livraison inclus"],
  },
  pack_visibilite: {
    id: "pack_visibilite",
    kind: "pack",
    name: "Pack Visibilité",
    shortName: "Pack Visibilité",
    price: 8900,
    value: 10790,
    description: "Avis, réseaux et multi-liens réunis dans une identité cohérente.",
    format: "2 Plaques 12 × 12 · 1 Carte multi-liens · 2 destinations",
    badge: "Avis + réseaux",
    defaultAction: "instagram",
    features: ["Deux messages, une même identité", "Destinations distinctes", "BAT et livraison inclus"],
  },
  pack_commerce: {
    id: "pack_commerce",
    kind: "pack",
    name: "Pack Commerce",
    shortName: "Pack Commerce",
    price: 14900,
    value: 17770,
    description: "Le comptoir, le mur et l’équipe couverts avec une seule direction graphique.",
    format: "1 Comptoir A6 · 1 Plaque 12 × 12 · 3 Cartes",
    badge: "Recommandé",
    defaultAction: "avis",
    pilotMonths: 3,
    features: ["Jusqu’à 5 destinations", "BAT prioritaire", "3 mois de Pilot à son ouverture"],
  },
  pack_resto: {
    id: "pack_resto",
    kind: "pack",
    name: "Pack Restaurant",
    shortName: "Pack Restaurant",
    price: 19900,
    value: 21790,
    description: "Une installation complète du comptoir aux tables, jusqu’à la vitrine.",
    format: "1 Comptoir A6 · 6 Tables A6 · 1 Vitrine",
    badge: "8 points de contact",
    defaultAction: "menu",
    pilotMonths: 3,
    features: ["Liens ou numéros individualisés", "BAT et configuration complète", "3 mois de Pilot à son ouverture"],
  },
  pack_salon: {
    id: "pack_salon",
    kind: "pack",
    name: "Pack Salon",
    shortName: "Pack Salon",
    price: 8900,
    value: 9800,
    description: "Deux comptoirs coordonnés pour demander un avis et faciliter la réservation.",
    format: "2 Comptoirs A6 · 2 destinations",
    badge: "Avis + réservation",
    defaultAction: "reservation",
    features: ["Deux messages complémentaires", "Une identité graphique commune", "BAT et livraison inclus"],
  },
  pack_equipe: {
    id: "pack_equipe",
    kind: "pack",
    name: "Pack Équipe",
    shortName: "Pack Équipe",
    price: 16900,
    value: 20930,
    description: "Six cartes pour le terrain et une Vitrine pour garder le contact après la visite.",
    format: "6 Cartes · 1 Vitrine · jusqu’à 7 destinations",
    badge: "Équipe mobile",
    defaultAction: "contact",
    features: ["Cartes nominatives possibles", "Liens distincts par collaborateur", "BAT et livraison inclus"],
  },
};

export const MULTISITE_TIERS = [
  { quantity: 3, price: 9900 },
  { quantity: 5, price: 15900 },
  { quantity: 10, price: 29900 },
];

export const ACTIONS = {
  avis: { id: "avis", name: "Avis Google", headline: "Votre avis compte.", subline: "30 secondes suffisent", category: "confiance", icon: "star", badge: "AVIS GOOGLE" },
  formulaire: { id: "formulaire", name: "Satisfaction", headline: "Comment c’était ?", subline: "Votre retour nous aide", category: "confiance", icon: "message", badge: "VOTRE AVIS" },
  menu: { id: "menu", name: "Menu", headline: "La carte, juste ici.", subline: "Toujours à jour", category: "service", icon: "menu", badge: "MENU" },
  reservation: { id: "reservation", name: "Réservation", headline: "On se revoit quand ?", subline: "Réservez en 30 secondes", category: "service", icon: "calendar", badge: "RÉSERVATION" },
  commande: { id: "commande", name: "Commander", headline: "Votre envie, maintenant.", subline: "Commandez en ligne", category: "service", icon: "bag", badge: "COMMANDE" },
  paiement: { id: "paiement", name: "Paiement", headline: "Réglez en un geste.", subline: "Simple et sécurisé", category: "service", icon: "card", badge: "PAIEMENT" },
  pourboire: { id: "pourboire", name: "Pourboire", headline: "Un merci pour l’équipe ?", subline: "Direct et sans espèces", category: "service", icon: "coins", badge: "POURBOIRE" },
  fidelite: { id: "fidelite", name: "Fidélité", headline: "Vos points vous attendent.", subline: "Revenez, on s’occupe du reste", category: "relation", icon: "gift", badge: "FIDÉLITÉ" },
  instagram: { id: "instagram", name: "Instagram", headline: "Suivez le mouvement.", subline: "Les coulisses sont ici", category: "relation", icon: "instagram", badge: "INSTAGRAM" },
  tiktok: { id: "tiktok", name: "TikTok", headline: "La suite se passe ici.", subline: "Suivez nos créations", category: "relation", icon: "music", badge: "TIKTOK" },
  facebook: { id: "facebook", name: "Facebook", headline: "Restons en contact.", subline: "Actualités et communauté", category: "relation", icon: "facebook", badge: "FACEBOOK" },
  linkedin: { id: "linkedin", name: "LinkedIn", headline: "Connectons nos projets.", subline: "Retrouvez-nous en ligne", category: "relation", icon: "linkedin", badge: "LINKEDIN" },
  wifi: { id: "wifi", name: "Wi-Fi", headline: "Connectez-vous ici.", subline: "Sans demander le mot de passe", category: "acces", icon: "wifi", badge: "WI-FI INVITÉ" },
  site: { id: "site", name: "Site internet", headline: "Découvrez notre univers.", subline: "Tout commence ici", category: "acces", icon: "globe", badge: "SITE INTERNET" },
  contact: { id: "contact", name: "Contact", headline: "Gardons le contact.", subline: "Coordonnées en un geste", category: "acces", icon: "mail", badge: "CONTACT" },
  whatsapp: { id: "whatsapp", name: "WhatsApp", headline: "Écrivez-nous ici.", subline: "Une réponse, simplement", category: "acces", icon: "message", badge: "WHATSAPP" },
  multiliens: { id: "multiliens", name: "Page multi-liens", headline: "Tout est juste ici.", subline: "Vos liens, une seule entrée", category: "acces", icon: "grid", badge: "VOS LIENS" },
  autre: { id: "autre", name: "Autre lien", headline: "Le bon lien. Maintenant.", subline: "Une destination sur mesure", category: "acces", icon: "link", badge: "LIEN PERSONNALISÉ" },
};

export const ACTION_CATEGORIES = {
  confiance: { id: "confiance", name: "Confiance", description: "Avis et satisfaction" },
  service: { id: "service", name: "Vendre & servir", description: "Menu, réservation et paiement" },
  relation: { id: "relation", name: "Fidéliser", description: "Réseaux et fidélité" },
  acces: { id: "acces", name: "Accès rapide", description: "Wi-Fi, site et contact" },
};

export const TARGETS = {
  cafe: { id: "cafe", name: "Café & bar", description: "Avis au comptoir, Wi-Fi et fidélité.", actionId: "avis", productId: "comptoir", theme: "blue", designStyle: "signature", exampleBrand: "CAFÉ NOMA" },
  restaurant: { id: "restaurant", name: "Restaurant", description: "Menu, avis et commande au comptoir.", actionId: "menu", productId: "comptoir", theme: "green", designStyle: "editorial", exampleBrand: "L’ATELIER 21" },
  salon: { id: "salon", name: "Beauté & bien-être", description: "Réservation, avis et Instagram.", actionId: "reservation", productId: "plaque", theme: "rose", designStyle: "platform", exampleBrand: "STUDIO LUNE" },
  boutique: { id: "boutique", name: "Boutique", description: "Fidélité, réseaux et catalogue.", actionId: "fidelite", productId: "plaque", theme: "sand", designStyle: "signature", exampleBrand: "MAISON ÉCLAT" },
  hotel: { id: "hotel", name: "Hôtel & location", description: "Wi-Fi, services et satisfaction séjour.", actionId: "wifi", productId: "plaque", theme: "mono", designStyle: "minimal", exampleBrand: "HÔTEL RIVAGE" },
  artisan: { id: "artisan", name: "Artisan & terrain", description: "Contact, devis et portfolio mobile.", actionId: "contact", productId: "carte", theme: "blue", designStyle: "signature", exampleBrand: "ATELIER MARTIN" },
  immobilier: { id: "immobilier", name: "Immobilier", description: "Contact, estimation et biens disponibles.", actionId: "multiliens", productId: "carte", theme: "mono", designStyle: "minimal", exampleBrand: "AGENCE HORIZON" },
  evenement: { id: "evenement", name: "Événement & équipe", description: "Programme, inscription et réseaux.", actionId: "site", productId: "plaque", theme: "blue", designStyle: "editorial", exampleBrand: "LE BON MOMENT" },
};

export const DESIGN_STYLES = {
  signature: { id: "signature", name: "Signature", description: "La marque en premier" },
  platform: { id: "platform", name: "Action", description: "L’objectif très lisible" },
  editorial: { id: "editorial", name: "Éditorial", description: "Une accroche forte" },
  minimal: { id: "minimal", name: "Minimal", description: "Sobre et premium" },
};

export const PILOT_PLANS = {
  pilot: { id: "pilot", name: "Tapote Pilot", price: 900 },
  annual: { id: "annual", name: "Tapote Pilot annuel", price: 8900 },
};

export const formatMoney = (cents) =>
  new Intl.NumberFormat("fr-FR", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: cents % 100 === 0 ? 0 : 2,
  }).format(cents / 100);
