export const SHIPPING = {
  freeThreshold: 6900,
  standardPrice: 490,
};

export const calculateShipping = (subtotal) => (
  subtotal >= SHIPPING.freeThreshold ? 0 : SHIPPING.standardPrice
);

export const matchingIdentityKey = (item = {}) => JSON.stringify({
  actionId: item.actionId || "",
  brandName: item.brandName || "",
  brandLogoId: item.brandLogoId || "",
  primaryColor: item.primaryColor || "",
  secondaryColor: item.secondaryColor || "",
  textColor: item.textColor || "",
  theme: item.theme || "",
  targetId: item.targetId || "",
  destinationUrl: item.destinationUrl || "",
  customHeadline: item.customHeadline || "",
  customSubline: item.customSubline || "",
  customTapLabel: item.customTapLabel || "",
});

export const PRODUCTS = {
  plaque_standard: {
    id: "plaque_standard",
    baseProductId: "plaque",
    personalization: "ready",
    kind: "support",
    name: "Tapote Plaque · Prête à poser",
    shortName: "Plaque",
    price: 5900,
    description: "Un design Tapote prêt à poser, avec votre destination déjà configurée.",
    format: "Support fixe · finition confirmée avant production · NFC + QR",
    badge: "Prête à poser",
    previewType: "square",
    recommendedFor: "Avis, réseaux et réservation",
    public: true,
  },
  plaque: {
    id: "plaque",
    baseProductId: "plaque",
    personalization: "custom",
    kind: "support",
    name: "Tapote Plaque",
    shortName: "Plaque",
    price: 7900,
    description: "Une plaque compacte, personnalisée pour votre marque et prête à poser.",
    format: "Support fixe · finition confirmée avant production · NFC + QR",
    badge: "Mur ou comptoir",
    previewType: "square",
    recommendedFor: "Avis, réseaux et réservation",
    public: true,
  },
  comptoir_standard: {
    id: "comptoir_standard",
    baseProductId: "comptoir",
    personalization: "ready",
    kind: "support",
    name: "Tapote Comptoir · Prêt à poser",
    shortName: "Comptoir",
    price: 6900,
    description: "Le support de comptoir signature avec un design Tapote prêt à poser.",
    format: "Support A6 fini · finition validée sur BAT · NFC + QR",
    badge: "Prêt à poser",
    previewType: "portrait",
    recommendedFor: "Caisse, accueil et table",
    public: true,
  },
  comptoir: {
    id: "comptoir",
    baseProductId: "comptoir",
    personalization: "custom",
    kind: "support",
    name: "Tapote Comptoir",
    shortName: "Comptoir",
    price: 8900,
    description: "Le support signature, visible à l’accueil et entièrement à votre image.",
    format: "Support A6 fini · finition validée sur BAT · NFC + QR",
    badge: "Le plus choisi",
    previewType: "portrait",
    recommendedFor: "Caisse, accueil et table",
    public: true,
  },
  carte_standard: {
    id: "carte_standard",
    baseProductId: "carte",
    personalization: "ready",
    kind: "card",
    name: "Tapote Card · Prête à poser",
    shortName: "Tapote Card",
    price: 3900,
    description: "Le format poche avec un design Tapote prêt et votre lien déjà configuré.",
    format: "Support mobile · finition confirmée avant production · NFC + QR",
    badge: "Petit prix",
    previewType: "landscape",
    recommendedFor: "Équipe et terrain",
    public: true,
  },
  carte: {
    id: "carte",
    baseProductId: "carte",
    personalization: "custom",
    kind: "card",
    name: "Tapote Card",
    shortName: "Tapote Card",
    price: 5900,
    description: "Votre Tapote de poche pour le terrain, les visites et les équipes.",
    format: "Support mobile · finition confirmée avant production · NFC + QR",
    badge: "Mobile",
    previewType: "landscape",
    recommendedFor: "Équipe et terrain",
    public: true,
  },
  pack_duo_standard: {
    id: "pack_duo_standard",
    baseProductId: "pack_duo",
    personalization: "ready",
    kind: "pack",
    name: "Pack Local · Prêt à poser",
    shortName: "Pack Local",
    price: 11900,
    value: 12800,
    supportCount: 2,
    defaultComposition: { comptoir: 1, plaque: 1 },
    description: "Un Comptoir et une Plaque avec un design Tapote prêt à poser, pour couvrir caisse et entrée.",
    format: "1 Comptoir + 1 Plaque",
    badge: "Parcours essentiel",
    defaultAction: "avis",
    features: ["1 Comptoir + 1 Plaque", "Design Tapote prêt", "Deux destinations initiales possibles"],
    public: true,
  },
  pack_duo: {
    id: "pack_duo",
    baseProductId: "pack_duo",
    personalization: "custom",
    kind: "pack",
    name: "Pack Local · À votre image",
    shortName: "Pack Local",
    price: 15900,
    value: 16800,
    supportCount: 2,
    defaultComposition: { comptoir: 1, plaque: 1 },
    description: "Un Comptoir et une Plaque coordonnés, avec votre identité de la caisse à l’entrée.",
    format: "1 Comptoir + 1 Plaque",
    badge: "Le plus choisi",
    defaultAction: "avis",
    features: ["1 Comptoir + 1 Plaque", "Logo, couleurs et textes personnalisables", "Deux destinations initiales possibles"],
    public: true,
  },
  pack_cinq_standard: {
    id: "pack_cinq_standard",
    baseProductId: "pack_cinq",
    personalization: "ready",
    kind: "pack",
    name: "Lot historique · 5 supports · Prêt à poser",
    shortName: "Lot historique · 5 supports",
    price: 29900,
    value: 31500,
    supportCount: 5,
    defaultComposition: { comptoir: 2, plaque: 3 },
    description: "Cinq supports issus de l’ancienne offre, conservés pour les commandes historiques.",
    format: "2 Comptoirs + 3 Plaques",
    badge: "Meilleur prix",
    defaultAction: "avis",
    features: ["2 Comptoirs + 3 Plaques", "Design Tapote prêt", "Liens distincts possibles"],
    public: false,
  },
  pack_cinq: {
    id: "pack_cinq",
    baseProductId: "pack_cinq",
    personalization: "custom",
    kind: "pack",
    name: "Lot historique · 5 supports · À votre image",
    shortName: "Lot historique · 5 supports",
    price: 39900,
    value: 41500,
    supportCount: 5,
    defaultComposition: { comptoir: 2, plaque: 3 },
    description: "Cinq points de contact coordonnés pour couvrir tout un lieu ou une petite équipe.",
    format: "2 Comptoirs + 3 Plaques",
    badge: "Meilleur prix",
    defaultAction: "avis",
    features: ["2 Comptoirs + 3 Plaques", "Identité cohérente", "Liens distincts possibles"],
    public: false,
  },
  carte_assortie: {
    id: "carte_assortie",
    baseProductId: "carte",
    personalization: "matched",
    kind: "addon",
    name: "La Carte NFC assortie",
    shortName: "Carte NFC assortie",
    price: 3900,
    value: 5900,
    requiresSupportOrder: true,
    description: "La même identité en poche, ajoutée à une commande de plaque ou de chevalet.",
    format: "Carte imprimée · même identité graphique · NFC + QR",
    badge: "Avec un support",
    previewType: "landscape",
    recommendedFor: "Équipe et terrain",
    public: false,
  },
};

export const PUBLIC_PRODUCT_IDS = Object.freeze(
  Object.values(PRODUCTS).filter((product) => product.public).map((product) => product.id),
);

export const isPublicProductId = (productId) => PUBLIC_PRODUCT_IDS.includes(productId);

export const MULTISITE_TIERS = [
  { quantity: 10, price: null, label: "Sur devis" },
];

export const ACTIONS = {
  avis: { id: "avis", name: "Avis Google", purpose: "Laissez un avis Google", tapoteFor: "PARTAGER VOTRE AVIS", campaignHeadline: "Vous avez aimé ? Tapotez.", campaignSubline: "30 secondes suffisent", visualKey: "rating", headline: "Votre avis compte.", subline: "30 secondes suffisent", category: "confiance", icon: "star", badge: "AVIS GOOGLE" },
  formulaire: { id: "formulaire", name: "Formulaire / demande", purpose: "Remplissez le formulaire", tapoteFor: "LANCER VOTRE DEMANDE", campaignHeadline: "Un projet ? Tapotez.", campaignSubline: "On vous répond rapidement", visualKey: "form", headline: "Votre demande commence ici.", subline: "Devis, inscription ou retour", category: "contact", icon: "message", badge: "FORMULAIRE" },
  menu: { id: "menu", name: "Menu", purpose: "Consultez le menu", tapoteFor: "DÉCOUVRIR LA CARTE", campaignHeadline: "Une envie ? Tapotez.", campaignSubline: "La carte toujours à jour", visualKey: "menu", headline: "La carte, juste ici.", subline: "Toujours à jour", category: "service", icon: "menu", badge: "MENU" },
  reservation: { id: "reservation", name: "Réservation", purpose: "Réservez votre créneau", tapoteFor: "RÉSERVER VOTRE MOMENT", campaignHeadline: "On se revoit ? Tapotez.", campaignSubline: "Votre créneau en 30 secondes", visualKey: "calendar", headline: "On se revoit quand ?", subline: "Réservez en 30 secondes", category: "service", icon: "calendar", badge: "RÉSERVATION" },
  commande: { id: "commande", name: "Commander", purpose: "Commandez en ligne", tapoteFor: "COMMANDER", campaignHeadline: "Ça vous tente ? Tapotez.", campaignSubline: "Click & collect ou livraison", visualKey: "order", headline: "Votre envie, maintenant.", subline: "Click & collect ou livraison", category: "service", icon: "bag", badge: "COMMANDE" },
  paiement: { id: "paiement", name: "Paiement", purpose: "Réglez ici", tapoteFor: "RÉGLER EN UN GESTE", campaignHeadline: "Pour régler ? Tapotez.", campaignSubline: "Simple, rapide et sécurisé", visualKey: "payment", headline: "Réglez en un geste.", subline: "Simple et sécurisé", category: "service", icon: "card", badge: "PAIEMENT" },
  pourboire: { id: "pourboire", name: "Pourboire", purpose: "Laissez un pourboire", tapoteFor: "DIRE MERCI", campaignHeadline: "Un merci ? Tapotez.", campaignSubline: "Simple, discret, sans espèces", visualKey: "thanks", headline: "Un merci pour l’équipe ?", subline: "Direct et sans espèces", category: "service", icon: "coins", badge: "POURBOIRE" },
  fidelite: { id: "fidelite", name: "Fidélité", purpose: "Rejoignez notre fidélité", tapoteFor: "REJOINDRE LES HABITUÉS", campaignHeadline: "Des avantages ? Tapotez.", campaignSubline: "À chaque visite, ça compte", visualKey: "loyalty", headline: "Vos points vous attendent.", subline: "Revenez, on s’occupe du reste", category: "relation", icon: "gift", badge: "FIDÉLITÉ" },
  instagram: { id: "instagram", name: "Instagram", purpose: "Suivez-nous sur Instagram", tapoteFor: "VOIR LES COULISSES", campaignHeadline: "Les coulisses ? Tapotez.", campaignSubline: "Créations, nouveautés, moments forts", visualKey: "instagram", headline: "Suivez le mouvement.", subline: "Les coulisses sont ici", category: "relation", icon: "instagram", badge: "INSTAGRAM" },
  tiktok: { id: "tiktok", name: "TikTok", purpose: "Suivez-nous sur TikTok", tapoteFor: "PASSER EN COULISSES", campaignHeadline: "La suite ? Tapotez.", campaignSubline: "Nos créations, sans recherche", visualKey: "tiktok", headline: "La suite se passe ici.", subline: "Suivez nos créations", category: "relation", icon: "music", badge: "TIKTOK" },
  facebook: { id: "facebook", name: "Facebook", purpose: "Retrouvez-nous sur Facebook", tapoteFor: "REJOINDRE LA COMMUNAUTÉ", campaignHeadline: "Restons proches. Tapotez.", campaignSubline: "Actualités et communauté locale", visualKey: "facebook", headline: "Restons en contact.", subline: "Actualités et communauté", category: "relation", icon: "facebook", badge: "FACEBOOK" },
  linkedin: { id: "linkedin", name: "LinkedIn", purpose: "Connectons-nous sur LinkedIn", tapoteFor: "CONNECTER NOS PROJETS", campaignHeadline: "Un projet commun ? Tapotez.", campaignSubline: "Le bon contact, au bon moment", visualKey: "linkedin", headline: "Connectons nos projets.", subline: "Retrouvez-nous en ligne", category: "relation", icon: "linkedin", badge: "LINKEDIN" },
  wifi: { id: "wifi", name: "Wi-Fi", purpose: "Connectez-vous au Wi-Fi", tapoteFor: "VOUS CONNECTER", campaignHeadline: "Besoin du Wi‑Fi ? Tapotez.", campaignSubline: "Le réseau invité en un geste", visualKey: "wifi", headline: "Connectez-vous ici.", subline: "Sans demander le mot de passe", category: "acces", icon: "wifi", badge: "WI-FI INVITÉ" },
  site: { id: "site", name: "Site internet", purpose: "Visitez notre site", tapoteFor: "DÉCOUVRIR LA SUITE", campaignHeadline: "Envie d’en voir plus ? Tapotez.", campaignSubline: "Votre univers s’ouvre ici", visualKey: "web", headline: "Découvrez notre univers.", subline: "Tout commence ici", category: "acces", icon: "globe", badge: "SITE INTERNET" },
  contact: { id: "contact", name: "Contact", purpose: "Enregistrez nos coordonnées", tapoteFor: "GARDER LE CONTACT", campaignHeadline: "On se rappelle ? Tapotez.", campaignSubline: "Nos coordonnées en un geste", visualKey: "contact", headline: "Gardons le contact.", subline: "Coordonnées en un geste", category: "acces", icon: "mail", badge: "CONTACT" },
  whatsapp: { id: "whatsapp", name: "WhatsApp", purpose: "Écrivez-nous sur WhatsApp", tapoteFor: "NOUS ÉCRIRE", campaignHeadline: "Une question ? Tapotez.", campaignSubline: "La conversation est déjà prête", visualKey: "whatsapp", headline: "Écrivez-nous ici.", subline: "Une réponse, simplement", category: "acces", icon: "message", badge: "WHATSAPP" },
  multiliens: { id: "multiliens", name: "Page multi-liens", purpose: "Accédez à tous nos liens", tapoteFor: "TOUT RETROUVER", campaignHeadline: "Tout retrouver ? Tapotez.", campaignSubline: "Services, horaires et liens utiles", visualKey: "links", headline: "Tout est juste ici.", subline: "Vos liens, une seule entrée", category: "acces", icon: "grid", badge: "VOS LIENS" },
  autre: { id: "autre", name: "Autre URL", purpose: "Ouvrez le lien", tapoteFor: "OUVRIR LE BON LIEN", campaignHeadline: "Le bon lien ? Tapotez.", campaignSubline: "Votre destination sur mesure", visualKey: "link", headline: "Le bon lien. Maintenant.", subline: "Une destination sur mesure", category: "acces", icon: "link", badge: "LIEN PERSONNALISÉ" },
};

export const ACTION_CATEGORIES = {
  confiance: { id: "confiance", name: "Confiance", description: "Avis et satisfaction" },
  service: { id: "service", name: "Vendre & servir", description: "Menu, réservation et paiement" },
  relation: { id: "relation", name: "Fidéliser", description: "Réseaux et fidélité" },
  acces: { id: "acces", name: "Accès rapide", description: "Wi-Fi, site et contact" },
};

export const TARGETS = {
  cafe: { id: "cafe", name: "Café & bar", description: "Avis au comptoir, Wi-Fi ou fidélité.", actionId: "avis", productId: "comptoir", theme: "nuit", exampleBrand: "VOTRE MARQUE" },
  restaurant: { id: "restaurant", name: "Restaurant", description: "Menu, réservation et avis au bon moment.", actionId: "menu", productId: "comptoir", theme: "nuit", exampleBrand: "L’ATELIER 21" },
  boulangerie: { id: "boulangerie", name: "Boulangerie", description: "Avis et fidélité à la caisse.", actionId: "avis", productId: "comptoir", theme: "creme", exampleBrand: "VOTRE MARQUE" },
  salon: { id: "salon", name: "Salon de coiffure", description: "Réservation, avis et Instagram.", actionId: "reservation", productId: "plaque", theme: "creme", exampleBrand: "STUDIO LUNE" },
  institut: { id: "institut", name: "Institut & spa", description: "Réservation, fidélité et soins.", actionId: "reservation", productId: "plaque", theme: "creme", exampleBrand: "MAISON CALME" },
  barber: { id: "barber", name: "Barbier", description: "Avis, réservation et réseaux.", actionId: "avis", productId: "comptoir", theme: "creme", exampleBrand: "LE COMPTOIR BARBER" },
  cabinet_medical: { id: "cabinet_medical", name: "Cabinet médical", description: "Informations et avis sans filtrage.", actionId: "formulaire", productId: "plaque", theme: "nuit", exampleBrand: "CABINET RIVOLI" },
  dentaire: { id: "dentaire", name: "Cabinet dentaire", description: "Avis, consignes et prise de rendez-vous.", actionId: "avis", productId: "plaque", theme: "nuit", exampleBrand: "DENTALYS" },
  kine: { id: "kine", name: "Kinésithérapeute", description: "Exercices, avis et prochain rendez-vous.", actionId: "reservation", productId: "plaque", theme: "nuit", exampleBrand: "MOUVEMENT KINÉ" },
  pharmacie: { id: "pharmacie", name: "Pharmacie", description: "Services, horaires et commande.", actionId: "multiliens", productId: "comptoir", theme: "nuit", exampleBrand: "PHARMACIE CENTRALE" },
  opticien: { id: "opticien", name: "Opticien", description: "Avis, rendez-vous et catalogue.", actionId: "reservation", productId: "plaque", theme: "nuit", exampleBrand: "REGARD PARIS" },
  boutique: { id: "boutique", name: "Boutique & retail", description: "Fidélité, réseaux et catalogue.", actionId: "fidelite", productId: "plaque", theme: "creme", exampleBrand: "MAISON ÉCLAT" },
  fleuriste: { id: "fleuriste", name: "Fleuriste", description: "Commande, avis et Instagram.", actionId: "commande", productId: "comptoir", theme: "nuit", exampleBrand: "FLEURS SAUVAGES" },
  hotel: { id: "hotel", name: "Hôtel", description: "Wi-Fi, services, guide et avis séjour.", actionId: "wifi", productId: "plaque", theme: "creme", exampleBrand: "HÔTEL RIVAGE" },
  gite: { id: "gite", name: "Gîte & location", description: "Guide d’arrivée, Wi-Fi et bonnes adresses.", actionId: "multiliens", productId: "plaque", theme: "creme", exampleBrand: "LA MAISON DOUCE" },
  camping: { id: "camping", name: "Camping", description: "Programme, services et plan du site.", actionId: "multiliens", productId: "comptoir", theme: "nuit", exampleBrand: "CAMPING DES PINS" },
  auto_ecole: { id: "auto_ecole", name: "Auto-école", description: "Avis, inscription et planning.", actionId: "avis", productId: "comptoir", theme: "nuit", exampleBrand: "DRIVE CLUB" },
  garage: { id: "garage", name: "Garage & contrôle technique", description: "Avis, devis et prochain entretien.", actionId: "avis", productId: "comptoir", theme: "creme", exampleBrand: "ATELIER AUTO" },
  artisan: { id: "artisan", name: "Artisan", description: "Contact, devis et portfolio sur le terrain.", actionId: "contact", productId: "carte", theme: "nuit", exampleBrand: "ATELIER MARTIN" },
  immobilier: { id: "immobilier", name: "Agence immobilière", description: "Estimation, biens et contact agent.", actionId: "multiliens", productId: "carte", theme: "creme", exampleBrand: "AGENCE HORIZON" },
  vtc: { id: "vtc", name: "VTC & taxi", description: "Avis, paiement et réservation.", actionId: "avis", productId: "carte", theme: "creme", exampleBrand: "RIVE DROITE VTC" },
  salle_sport: { id: "salle_sport", name: "Salle de sport", description: "Planning, inscription et réseaux.", actionId: "multiliens", productId: "plaque", theme: "nuit", exampleBrand: "MOTION CLUB" },
  yoga: { id: "yoga", name: "Yoga & pilates", description: "Planning, réservation et fidélité.", actionId: "reservation", productId: "plaque", theme: "creme", exampleBrand: "STUDIO ANCRAGE" },
  coworking: { id: "coworking", name: "Coworking", description: "Wi-Fi, salles et événements.", actionId: "wifi", productId: "comptoir", theme: "nuit", exampleBrand: "LE BUREAU LIBRE" },
  evenement: { id: "evenement", name: "Événement", description: "Programme, inscription et partenaires.", actionId: "site", productId: "plaque", theme: "nuit", exampleBrand: "LE BON MOMENT" },
  culture: { id: "culture", name: "Musée & lieu culturel", description: "Programme, audioguide et billetterie.", actionId: "multiliens", productId: "plaque", theme: "creme", exampleBrand: "LA GALERIE" },
  traiteur: { id: "traiteur", name: "Traiteur", description: "Commande, catalogue et demande de devis.", actionId: "commande", productId: "comptoir", theme: "nuit", exampleBrand: "MAISON SÉSON" },
  patisserie: { id: "patisserie", name: "Pâtisserie", description: "Commande, nouveautés et avis à la caisse.", actionId: "commande", productId: "comptoir", theme: "creme", exampleBrand: "SUCRE DOUX" },
  food_truck: { id: "food_truck", name: "Food truck", description: "Menu, paiement et position du jour.", actionId: "menu", productId: "plaque", theme: "nuit", exampleBrand: "MOBILE CLUB" },
  caviste: { id: "caviste", name: "Caviste", description: "Conseils, fidélité et prochaines dégustations.", actionId: "fidelite", productId: "comptoir", theme: "creme", exampleBrand: "LA BONNE BOUTEILLE" },
  tatoueur: { id: "tatoueur", name: "Tatoueur", description: "Portfolio, prise de rendez-vous et soins.", actionId: "instagram", productId: "plaque", theme: "creme", exampleBrand: "LIGNE NOIRE" },
  onglerie: { id: "onglerie", name: "Onglerie", description: "Réservation, inspirations et fidélité.", actionId: "reservation", productId: "plaque", theme: "creme", exampleBrand: "ATELIER NUDE" },
  veterinaire: { id: "veterinaire", name: "Clinique vétérinaire", description: "Urgences, rendez-vous et informations pratiques.", actionId: "multiliens", productId: "plaque", theme: "nuit", exampleBrand: "CLINIQUE DES LILAS" },
  toiletteur: { id: "toiletteur", name: "Toiletteur", description: "Réservation, tarifs et photos avant-après.", actionId: "reservation", productId: "comptoir", theme: "nuit", exampleBrand: "MUSEAU PROPRE" },
  osteopathe: { id: "osteopathe", name: "Ostéopathe", description: "Rendez-vous, conseils et informations du cabinet.", actionId: "reservation", productId: "plaque", theme: "creme", exampleBrand: "CABINET ÉQUILIBRE" },
  audioprothesiste: { id: "audioprothesiste", name: "Audioprothésiste", description: "Contrôle, rendez-vous et guide d’entretien.", actionId: "reservation", productId: "plaque", theme: "nuit", exampleBrand: "ÉCOUTE STUDIO" },
  agence_voyage: { id: "agence_voyage", name: "Agence de voyage", description: "Offres, rendez-vous et carnet de voyage.", actionId: "multiliens", productId: "comptoir", theme: "nuit", exampleBrand: "HORIZONS" },
  photographe: { id: "photographe", name: "Photographe", description: "Portfolio, galerie client et réservation.", actionId: "multiliens", productId: "carte", theme: "creme", exampleBrand: "STUDIO GABRIEL" },
  wedding_planner: { id: "wedding_planner", name: "Wedding planner", description: "Portfolio, prise de contact et prestataires.", actionId: "contact", productId: "carte", theme: "creme", exampleBrand: "OUI ATELIER" },
  salle_reception: { id: "salle_reception", name: "Salle de réception", description: "Visite, disponibilités et demande de devis.", actionId: "reservation", productId: "comptoir", theme: "creme", exampleBrand: "DOMAINE MARCEAU" },
  centre_formation: { id: "centre_formation", name: "Centre de formation", description: "Programme, inscription et ressources stagiaires.", actionId: "multiliens", productId: "plaque", theme: "nuit", exampleBrand: "CAMPUS 22" },
  ecole_langues: { id: "ecole_langues", name: "École de langues", description: "Test de niveau, planning et inscription.", actionId: "formulaire", productId: "comptoir", theme: "nuit", exampleBrand: "HELLO STUDIO" },
  association: { id: "association", name: "Association", description: "Adhésion, dons et prochains événements.", actionId: "multiliens", productId: "plaque", theme: "nuit", exampleBrand: "LE LIEN LOCAL" },
  office_tourisme: { id: "office_tourisme", name: "Office de tourisme", description: "Carte, agenda et bonnes adresses multilingues.", actionId: "multiliens", productId: "plaque", theme: "nuit", exampleBrand: "ICI & AUTOUR" },
};

export const PILOT_PLANS = {
  pilotPro: { id: "pilot_pro", name: "Tapote Pilot Pro", price: 900 },
  pilotProAnnual: { id: "pilot_pro_annual", name: "Tapote Pilot Pro annuel", price: 8900 },
  // Alias conservés pour les intégrations existantes ; l’offre publique porte
  // désormais explicitement le nom Pilot Pro.
  pilot: { id: "pilot_pro", name: "Tapote Pilot Pro", price: 900 },
  annual: { id: "pilot_pro_annual", name: "Tapote Pilot Pro annuel", price: 8900 },
};

export const formatMoney = (cents) =>
  new Intl.NumberFormat("fr-FR", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: cents % 100 === 0 ? 0 : 2,
  }).format(cents / 100);
